import image1 from "../../assets/post/post1_img.png";
import image2 from "../../assets/post/post2_img.png";
import image3 from "../../assets/post/post3_img.png";
const posts = [
  {
    postImage: image1,
    postType: "✍Article",
    postTitle: "What if famous brands had regular fonts? Meet RegulaBrands!",
    postBody: "I've worked in UX for the better part of a decade. From now on, I plan to rei…",
    postUser: "Sarthak Kamra",
    postViews: "1.4k",
    postDate: "",
    postLocation: "",
    postCompany: "",
    postButton: "",
  },
  {
    postImage: image2,
    postType: "👨‍🎓Education",
    postTitle: "Tax Benefits for Investment under National Pension Scheme launched by Government",
    postBody: "I've worked in UX for the better part of a decade. From now on, I plan to rei…",
    postUser: "Sarah West",
    postViews: "1.4k",
    postDate: "",
    postLocation: "",
    postCompany: "",
    postButton: "",
  },
  {
    postImage: image3,
    postType: "📅Meetup",
    postTitle: "Finance & Investment Elite Social Mixer @Lujiazui",
    postDate: "Fri,12 Oct,2018",
    postLocation: "Ahmedabad,India",
    postUser: "Ronal Jones",
    postViews: "1.4k",
    postCompany: "",
    postButton: "Visit Website",
    postBody: "",
  },
  {
    postImage: "",
    postType: "👜Job",
    postTitle: "Software Developer",
    postCompany: "Innovaccer Analytics Private Ltd.",
    postLocation: "Noida,India",
    postUser: "Joseph Gray",
    postViews: "1.4k",
    postBody: "",
    postDate: "",
    postButton: "Apply on Timesjobs",
  },
];
